### ISSUE TITLE
Ongoing: Add damaged interchange files for testing

### ISSUE THREAD

**Issue by cyberme0w** [cyberme0w/ebiz-project#50]
Every exception that we handle should be able to be tested by a file in `test_files`.
This means creating an invalid interchange on purpose that will trigger each specific exception we handle.
It would be good to have some tests handle this automagically in `run_tests.rb` but for this ticket it would be enough to have the files and throw them at the program manually.

**Comment by isilisi4** [comment]
Has been accomplished with latest tests added to master
